<?php

namespace App\Modules\Config\Support;

class DefaultConfig
{
    public static function items(): array
    {
        return [
            [
                'key' => 'milestone.amount',
                'group' => 'milestone',
                'name' => '里程碑金额',
                'type' => 'decimal',
                'value' => '100',
                'tips' => '新人累计充值每达到该金额，触发一次直接上级奖励',
                'sort' => 10,
            ],
            [
                'key' => 'milestone.reward_amount',
                'group' => 'milestone',
                'name' => '里程碑奖励金额',
                'type' => 'decimal',
                'value' => '15',
                'tips' => '每次里程碑触发时，直接上级获得的返利金额',
                'sort' => 20,
            ],
            [
                'key' => 'milestone.max_times',
                'group' => 'milestone',
                'name' => '里程碑次数上限',
                'type' => 'int',
                'value' => 2,
                'tips' => '同一个新人最多触发多少次里程碑奖励',
                'sort' => 30,
            ],
            [
                'key' => 'milestone.only_direct',
                'group' => 'milestone',
                'name' => '只奖励直接上级',
                'type' => 'bool',
                'value' => true,
                'tips' => '开启后，里程碑阶段只奖励直接上级',
                'sort' => 40,
            ],
            [
                'key' => 'rebate.stage_amount',
                'group' => 'rebate',
                'name' => '多级返利门槛',
                'type' => 'decimal',
                'value' => '100',
                'tips' => '下级完成里程碑阶段后，后续累计充值每满一次该金额，触发一次多级返利分配',
                'sort' => 50,
            ],
            [
                'key' => 'rebate.stage_reward_amount',
                'group' => 'rebate',
                'name' => '每次分配奖励池',
                'type' => 'decimal',
                'value' => '15',
                'tips' => '每次触发多级返利时，整条上级链路本次总共分配的奖励金额',
                'sort' => 55,
            ],
            [
                'key' => 'rebate.mode',
                'group' => 'rebate',
                'name' => '分发模式',
                'type' => 'string',
                'value' => 'decay',
                'tips' => '分发模式：decay 衰减系数模式',
                'sort' => 60,
            ],
            [
                'key' => 'rebate.decay_factor',
                'group' => 'rebate',
                'name' => '衰减系数',
                'type' => 'decimal',
                'value' => '0.4',
                'tips' => '衰减系数，每增加一级权重乘以该值，越小则上级集中度越高',
                'sort' => 70,
            ],
            [
                'key' => 'rebate.max_depth',
                'group' => 'rebate',
                'name' => '最大返利深度',
                'type' => 'int',
                'value' => 5,
                'tips' => '每次触发多级返利时，最多向上分配的层级数',
                'sort' => 72,
            ],
            [
                'key' => 'rebate.inactive_node_mode',
                'group' => 'rebate',
                'name' => '失效节点返利处理方式',
                'type' => 'string',
                'value' => 'platform',
                'tips' => 'platform 归平台；exclude_recalculate 排除失效节点后重算',
                'sort' => 75,
            ],
            [
                'key' => 'rebate.normalize',
                'group' => 'rebate',
                'name' => '归一化',
                'type' => 'bool',
                'value' => true,
                'tips' => '归一化后将返利池全部分配给有效上级',
                'sort' => 80,
            ],
            [
                'key' => 'rebate.recharge_bonus_100',
                'group' => 'rebate',
                'name' => '充值 100 赠送金额',
                'type' => 'decimal',
                'value' => '5',
                'tips' => '充值满 100 元时赠送的额度，0 表示该档不赠送',
                'sort' => 81,
            ],
            [
                'key' => 'rebate.recharge_bonus_200',
                'group' => 'rebate',
                'name' => '充值 200 赠送金额',
                'type' => 'decimal',
                'value' => '15',
                'tips' => '充值满 200 元时赠送的额度，0 表示该档不赠送',
                'sort' => 82,
            ],
            [
                'key' => 'rebate.recharge_bonus_500',
                'group' => 'rebate',
                'name' => '充值 500 赠送金额',
                'type' => 'decimal',
                'value' => '50',
                'tips' => '充值满 500 元时赠送的额度，0 表示该档不赠送',
                'sort' => 83,
            ],
            [
                'key' => 'rebate.recharge_bonus_1000',
                'group' => 'rebate',
                'name' => '充值 1000 赠送金额',
                'type' => 'decimal',
                'value' => '120',
                'tips' => '充值满 1000 元时赠送的额度，0 表示该档不赠送',
                'sort' => 84,
            ],
            [
                'key' => 'payment.cny_to_credit_rate',
                'group' => 'payment',
                'name' => '人民币额度换算比例',
                'type' => 'decimal',
                'value' => '1',
                'tips' => '充值 1 人民币默认换算为多少 API 额度',
                'sort' => 90,
            ],
            [
                'key' => 'payment.recharge_name',
                'group' => 'payment',
                'name' => '充值商品名称',
                'type' => 'string',
                'value' => '额度充值',
                'tips' => '提交给支付通道的商品名称，例如 额度充值',
                'sort' => 90,
            ],
            [
                'key' => 'payment.recharge_fee_rate',
                'group' => 'payment',
                'name' => '收款手续费比例',
                'type' => 'decimal',
                'value' => '0.6',
                'tips' => '收款通道扣费百分比，0.6 表示 0.6%；用户支付 10 元时商户实收 9.94 元',
                'sort' => 90,
            ],
            [
                'key' => 'payment.mode',
                'group' => 'payment',
                'name' => '支付通道模式',
                'type' => 'string',
                'value' => 'manual_qr',
                'tips' => 'manual_qr 手工二维码；epay Epay 自动回调',
                'sort' => 90,
            ],
            [
                'key' => 'payment.qr_enabled',
                'group' => 'payment',
                'name' => '二维码充值开关',
                'type' => 'bool',
                'value' => true,
                'tips' => '是否启用支付宝二维码充值',
                'sort' => 91,
            ],
            [
                'key' => 'payment.alipay_qr_url',
                'group' => 'payment',
                'name' => '支付宝二维码地址',
                'type' => 'string',
                'value' => '',
                'tips' => '支付宝收款二维码图片 URL，可填 CDN、对象存储或站内静态文件地址，也可保存 data URL',
                'sort' => 92,
            ],
            [
                'key' => 'payment.alipay_display_name',
                'group' => 'payment',
                'name' => '支付宝收款展示名',
                'type' => 'string',
                'value' => '',
                'tips' => '充值页展示的收款方名称，例如 张三(支付宝)',
                'sort' => 93,
            ],
            [
                'key' => 'payment.qr_note',
                'group' => 'payment',
                'name' => '二维码充值提示',
                'type' => 'string',
                'value' => '付款时请备注订单号，支付后点击“我已完成支付”等待审核到账。',
                'tips' => '充值页展示给用户的付款提示文案',
                'sort' => 94,
            ],
            [
                'key' => 'payment.order_expire_minutes',
                'group' => 'payment',
                'name' => '充值订单有效期',
                'type' => 'int',
                'value' => 15,
                'tips' => '二维码充值订单有效期，超时后需要重新创建订单',
                'sort' => 95,
            ],
            [
                'key' => 'payment.epay.enabled',
                'group' => 'payment',
                'name' => 'Epay 开关',
                'type' => 'bool',
                'value' => false,
                'tips' => '是否启用 Epay 当面付通道',
                'sort' => 96,
            ],
            [
                'key' => 'payment.epay.pid',
                'group' => 'payment',
                'name' => 'Epay 商户 PID',
                'type' => 'string',
                'value' => '',
                'tips' => 'Epay 商户 ID',
                'sort' => 97,
            ],
            [
                'key' => 'payment.epay.key',
                'group' => 'payment',
                'name' => 'Epay 商户 Key',
                'type' => 'string',
                'value' => '',
                'tips' => 'Epay 商户密钥，禁止提交到 Git',
                'sort' => 98,
            ],
            [
                'key' => 'payment.epay.gateway_url',
                'group' => 'payment',
                'name' => 'Epay 地址',
                'type' => 'string',
                'value' => 'https://pay.sjiaa.cc.cd',
                'tips' => 'Epay 服务地址，例如 https://pay.sjiaa.cc.cd',
                'sort' => 99,
            ],
            [
                'key' => 'payment.epay.notify_url',
                'group' => 'payment',
                'name' => 'Epay 回调地址',
                'type' => 'string',
                'value' => '',
                'tips' => '公网 HTTPS 回调地址，例如 https://domain.com/api/v1/recharge/epay/notify',
                'sort' => 100,
            ],
            [
                'key' => 'payment.epay.return_url',
                'group' => 'payment',
                'name' => 'Epay 返回地址',
                'type' => 'string',
                'value' => '',
                'tips' => '用户支付成功后返回的前端页面地址',
                'sort' => 101,
            ],
            [
                'key' => 'payment.epay.display_name',
                'group' => 'payment',
                'name' => 'Epay 展示名',
                'type' => 'string',
                'value' => 'Epay 当面付',
                'tips' => '充值页展示的支付通道名称',
                'sort' => 102,
            ],
            [
                'key' => 'payment.epay.sitename',
                'group' => 'payment',
                'name' => 'Epay 商户站点名',
                'type' => 'string',
                'value' => 'Sub2Rebate',
                'tips' => '提交给 Epay 的 sitename 参数',
                'sort' => 103,
            ],
            [
                'key' => 'payment.epay.type',
                'group' => 'payment',
                'name' => 'Epay 支付类型',
                'type' => 'string',
                'value' => 'alipay',
                'tips' => '提交给 Epay 的 type 参数，默认 alipay',
                'sort' => 104,
            ],
            [
                'key' => 'payment.alipay_transfer.enabled',
                'group' => 'payment',
                'name' => '支付宝转账开关',
                'type' => 'bool',
                'value' => false,
                'tips' => '开启后，管理员确认打款会调用支付宝单笔转账接口',
                'sort' => 105,
            ],
            [
                'key' => 'payment.alipay_transfer.auto_pay_enabled',
                'group' => 'payment',
                'name' => '审批后自动打款',
                'type' => 'bool',
                'value' => false,
                'tips' => '开启后，管理员审批通过支付宝提现时立即尝试自动打款',
                'sort' => 105,
            ],
            [
                'key' => 'payment.alipay_transfer.retry_enabled',
                'group' => 'payment',
                'name' => '自动重试打款',
                'type' => 'bool',
                'value' => false,
                'tips' => '开启后，定时任务会重试已审核但打款失败的支付宝提现',
                'sort' => 105,
            ],
            [
                'key' => 'payment.alipay_transfer.retry_interval_minutes',
                'group' => 'payment',
                'name' => '打款重试间隔',
                'type' => 'int',
                'value' => 5,
                'tips' => '每笔失败打款至少间隔多少分钟再自动重试',
                'sort' => 105,
            ],
            [
                'key' => 'payment.alipay_transfer.retry_batch_size',
                'group' => 'payment',
                'name' => '打款重试批量',
                'type' => 'int',
                'value' => 50,
                'tips' => '每次定时任务最多重试多少笔提现',
                'sort' => 105,
            ],
            [
                'key' => 'payment.alipay_transfer.gateway_url',
                'group' => 'payment',
                'name' => '支付宝转账网关',
                'type' => 'string',
                'value' => 'https://openapi.alipay.com/gateway.do',
                'tips' => '支付宝开放平台网关地址',
                'sort' => 106,
            ],
            [
                'key' => 'payment.alipay_transfer.app_id',
                'group' => 'payment',
                'name' => '支付宝应用 ID',
                'type' => 'string',
                'value' => '',
                'tips' => '支付宝开放平台应用 app_id',
                'sort' => 107,
            ],
            [
                'key' => 'payment.alipay_transfer.private_key',
                'group' => 'payment',
                'name' => '支付宝应用私钥',
                'type' => 'string',
                'value' => '',
                'tips' => 'RSA2 应用私钥，禁止提交到 Git',
                'sort' => 108,
            ],
            [
                'key' => 'payment.alipay_transfer.alipay_public_key',
                'group' => 'payment',
                'name' => '支付宝公钥',
                'type' => 'string',
                'value' => '',
                'tips' => '支付宝开放平台公钥，后续查询/验签使用',
                'sort' => 109,
            ],
            [
                'key' => 'payment.alipay_transfer.single_max_amount',
                'group' => 'payment',
                'name' => '支付宝单笔打款限额',
                'type' => 'decimal',
                'value' => '500',
                'tips' => '管理员单次自动打款不能超过该金额',
                'sort' => 110,
            ],
            [
                'key' => 'payment.alipay_transfer.daily_limit_amount',
                'group' => 'payment',
                'name' => '支付宝每日打款限额',
                'type' => 'decimal',
                'value' => '5000',
                'tips' => '当天自动打款总额不能超过该金额',
                'sort' => 111,
            ],
            [
                'key' => 'payment.alipay_transfer.identity_type',
                'group' => 'payment',
                'name' => '支付宝收款标识类型',
                'type' => 'string',
                'value' => 'ALIPAY_LOGON_ID',
                'tips' => 'ALIPAY_LOGON_ID 或 ALIPAY_USER_ID',
                'sort' => 112,
            ],
            [
                'key' => 'payment.alipay_transfer.order_title',
                'group' => 'payment',
                'name' => '支付宝转账标题',
                'type' => 'string',
                'value' => '返利提现',
                'tips' => '支付宝收款方看到的转账标题',
                'sort' => 113,
            ],
            [
                'key' => 'withdraw.min_amount',
                'group' => 'withdraw',
                'name' => '最低提现金额',
                'type' => 'decimal',
                'value' => '50',
                'tips' => '最低提现金额',
                'sort' => 100,
            ],
            [
                'key' => 'withdraw.review_mode',
                'group' => 'withdraw',
                'name' => '提现审核模式',
                'type' => 'string',
                'value' => 'manual',
                'tips' => '审核模式：manual 人工审核',
                'sort' => 110,
            ],
            [
                'key' => 'withdraw.daily_limit',
                'group' => 'withdraw',
                'name' => '每日提现次数',
                'type' => 'int',
                'value' => 1,
                'tips' => '每日提现次数上限',
                'sort' => 120,
            ],
            [
                'key' => 'withdraw.freeze_days',
                'group' => 'withdraw',
                'name' => '返利冻结天数',
                'type' => 'int',
                'value' => 0,
                'tips' => '新获得返利冻结天数，0 为不冻结',
                'sort' => 130,
            ],
            [
                'key' => 'withdraw.to_api_quota_enabled',
                'group' => 'withdraw',
                'name' => '转入 API 额度开关',
                'type' => 'bool',
                'value' => true,
                'tips' => '是否允许用户把返利余额即时转入 Sub2API 额度',
                'sort' => 135,
            ],
            [
                'key' => 'withdraw.to_api_quota_rate',
                'group' => 'withdraw',
                'name' => 'API 额度换算比例',
                'type' => 'decimal',
                'value' => '1',
                'tips' => '返利余额 1 元默认转入 1 API 额度',
                'sort' => 136,
            ],
            [
                'key' => 'risk.blacklist_enabled',
                'group' => 'risk',
                'name' => '启用黑名单',
                'type' => 'bool',
                'value' => true,
                'tips' => '是否启用黑名单',
                'sort' => 140,
            ],
            [
                'key' => 'risk.duplicate_check',
                'group' => 'risk',
                'name' => '防重复发放检查',
                'type' => 'bool',
                'value' => true,
                'tips' => '是否启用返利事件防重复发放检查',
                'sort' => 150,
            ],
            [
                'key' => 'risk.lie_flat_enabled',
                'group' => 'risk',
                'name' => '启用防躺平检测',
                'type' => 'bool',
                'value' => true,
                'tips' => '连续无充值、余额无减少、无新增下级时，自动暂停返利资格',
                'sort' => 160,
            ],
            [
                'key' => 'risk.lie_flat_days',
                'group' => 'risk',
                'name' => '连续无活跃天数',
                'type' => 'int',
                'value' => 7,
                'tips' => '防躺平检测的连续无活跃天数，默认 7 天',
                'sort' => 170,
            ],
            [
                'key' => 'risk.lie_flat_restore_min_recharge',
                'group' => 'risk',
                'name' => '置灰恢复最低充值金额',
                'type' => 'decimal',
                'value' => '10',
                'tips' => '用户被防躺平置灰后，充值成功回调确认的单次金额必须大于等于该值才会恢复返利资格；余额监控只记录活跃，不恢复资格',
                'sort' => 180,
            ],
        ];
    }

    public static function byKey(): array
    {
        $items = [];
        foreach (self::items() as $item) {
            $items[$item['key']] = $item;
        }

        return $items;
    }
}
